### ISSUE TITLE
KNP Version and LICENSE error when build KNP as a third-party.

### ISSUE THREAD

**Issue by LandauSchwinger** [KasperskyLab/knp#10]
I've tried to load KNP as third-party component with CPM and encounter several errors:
1. CMake of KNP can't find LICENSE and README files (possible solution - change CMAKE_SOURCE_DIR to CMAKE_CURRENT_SOURCE_DIR)
2. KNP start to build itself in project third-party folder, but then start to build itself one more time inside third-party folder of knp itself.

**Comment by artiomn** [comment]
Thank you, we will fix this.

**Comment by artiomn** [comment]
Ok, you fixed this already. :-)

**Comment by artiomn** [comment]
Thank you.
