### ISSUE TITLE
Unable to load knp-cpu-multi-threaded-backend via backend loader

### ISSUE THREAD

**Issue by maxkost** [KasperskyLab/knp#2]
When trying to change `knp-cpu-single-threaded-backend` to `knp-cpu-multi-threaded-backend` in the [simple-network example](https://github.com/KasperskyLab/knp/blob/master/examples/simple-network/main.cpp#L111) it crashes with an error:
```
[2024-11-11 16:07:51.983] [info] [backend_loader.cpp:44] Loading backend by path "./bin/knp-cpu-multi-threaded-backend"...
terminate called after throwing an instance of 'boost::wrapexcept<boost::system::system_error>'
  what():  boost::dll::shared_library::get() failed (dlerror system message: ./bin/libknp-cpu-multi-threaded-backend.so: undefined symbol: create_knp_backend): Illegal seek [generic:29]
[1]    21049 IOT instruction (core dumped)  ./bin/simple-network
```
This seems to be due to the wrong symbol name:
https://github.com/KasperskyLab/knp/blob/master/knp/backends/cpu/cpu-multi-threaded-backend/include/knp/backends/cpu-multi-threaded/backend.h#L367

**Comment by artiomn** [comment]
Was the backend compiled with the KNP framework or separately?

**Comment by maxkost** [comment]
It was compiled from KNP framework sources(this repo).

**Comment by artiomn** [comment]
@maxkost do you have e-mail to contact directly?

**Comment by maxkost** [comment]
@artiomn, maximkostyukov@yandex.ru

**Comment by artiomn** [comment]
I've written, thank you.
